### ISSUE TITLE
Merge into DataStructures.jl

### ISSUE THREAD

**Issue by SyxP** [byhill/DisjointSets.jl#1]
Is there a reason why this package is not merged into DataStructures? From what I understand union by size is the same time complexity as union by rank (with path-compression), and the memory is the same as one needs to store the rank anyway. (It is true that rank can be stored in a `UInt8` for all practical purposes, which could give a 4-8x savings in memory)

**Comment by byhill** [comment]
Using union by size allows one to find the size of the set containing some element `x` in near constant time.  Using union by rank doesn't allow for this.  I did make a pull request a few months ago on DataCollections.jl to switch from union-by-rank to union-by-size [here](https://github.com/JuliaCollections/DataStructures.jl/pull/842), but I haven't received a review yet and I don't want to continue waiting for one.

**Comment by byhill** [comment]
Also, I should add, if you are a maintainer of DataStructures.jl, I'm more than willing to make a new pull-request and have it reviewed.  I do want a disjoint-set data structure that allows me to easily find the size of a set, so if DataStructures.jl is willing to let me add that, I'll happily make a pull-request :)
